In [1]:
import math
import pandas as pd

In [3]:
df = pd.read_csv('nba_players.csv')

In [4]:
df.head()

,Unnamed: 0,Player,Ht,Wt,Colleges,Pos,Age,Tm,G,GS,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,Alaa Abdelnaby,6-10,240.0,Duke,PF,22,POR,43,0,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
1,1,Danny Ainge,6-4,175.0,BYU,SG,31,POR,80,0,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
2,2,Mark Bryant,6-9,245.0,Seton Hall,PF,25,POR,53,0,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
3,3,Wayne Cooper,6-10,220.0,New Orleans,C,34,POR,67,1,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
4,4,Walter Davis,6-6,193.0,UNC,SG,36,POR,71,14,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47

In [5]:
df['Team'].value_counts()

Team
Philadelphia 76ers                   664
Golden State Warriors                659
Cleveland Cavaliers                  657
San Antonio Spurs                    655
Atlanta Hawks                        653
Houston Rockets                      652
Milwaukee Bucks                      648
Boston Celtics                       643
New York Knicks                      642
Denver Nuggets                       635
Indiana Pacers                       634
Detroit Pistons                      633
Chicago Bulls                        625
Dallas Mavericks                     625
Los Angeles Lakers                   624
Phoenix Suns                         622
Portland Trail Blazers               617
Los Angeles Clippers                 615
Utah Jazz                            614
Sacramento Kings                     542
Miami Heat                           522
New Jersey Nets                      508
Orlando Magic                        493
Minnesota Timberwolves               489
Toronto Raptors                      425
Seattle SuperSonics                  419
Washington Wizards                   391
Memphis Grizzlies                    334
Charlotte Hornets                    325
Washington Bullets                   291
Oklahoma City Thunder                215
Charlotte Bobcats                    166
Brooklyn Nets                        166
New Orleans Pelicans                 147
New Orleans Hornets                  146
Vancouver Grizzlies                   90
Kansas City Kings                     85
San Diego Clippers                    73
New Orleans/Oklahoma City Hornets     32
Name: count, dtype: int64

Probability

In [6]:
def nCr(n,k):
    f = math.factorial
    return f(n)/ (f(k) * f(n - k))

In [ ]:
nCr(12,2)

495.0

In [8]:
nCr(2,2)

1.0

In [10]:
nCr(3,2)

3.0

implementing birthday_probability function

In [11]:
1 - ((364/365)) ** nCr(10,2)

0.11614023654879224

In [12]:
def birthday_probability(number_of_people):
    return 1 - ((314/316))**nCr(number_of_people,2)
birthday_probability(15)

0.48658403081125223

NBA BITHDAY PARADOX ANALYSIS

In [18]:
df = pd.read_csv("nba_players.csv",parse_dates=['Age'])

C:\Users\divya\AppData\Local\Temp\ipykernel_11760\2320261498.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("nba_players.csv",parse_dates=['Age'])

In [15]:
df.head()

,Unnamed: 0,Player,Ht,Wt,Colleges,Pos,Age,Tm,G,GS,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,Alaa Abdelnaby,6-10,240.0,Duke,PF,22,POR,43,0,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
1,1,Danny Ainge,6-4,175.0,BYU,SG,31,POR,80,0,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
2,2,Mark Bryant,6-9,245.0,Seton Hall,PF,25,POR,53,0,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
3,3,Wayne Cooper,6-10,220.0,New Orleans,C,34,POR,67,1,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47
4,4,Walter Davis,6-6,193.0,UNC,SG,36,POR,71,14,...,0.0,0.0,Portland Trail Blazers,63,19,0.768,0.0,114.7,106.0,8.47

In [19]:
df['Team'].value_counts()

Team
Philadelphia 76ers                   664
Golden State Warriors                659
Cleveland Cavaliers                  657
San Antonio Spurs                    655
Atlanta Hawks                        653
Houston Rockets                      652
Milwaukee Bucks                      648
Boston Celtics                       643
New York Knicks                      642
Denver Nuggets                       635
Indiana Pacers                       634
Detroit Pistons                      633
Chicago Bulls                        625
Dallas Mavericks                     625
Los Angeles Lakers                   624
Phoenix Suns                         622
Portland Trail Blazers               617
Los Angeles Clippers                 615
Utah Jazz                            614
Sacramento Kings                     542
Miami Heat                           522
New Jersey Nets                      508
Orlando Magic                        493
Minnesota Timberwolves               489
Toronto Raptors                      425
Seattle SuperSonics                  419
Washington Wizards                   391
Memphis Grizzlies                    334
Charlotte Hornets                    325
Washington Bullets                   291
Oklahoma City Thunder                215
Charlotte Bobcats                    166
Brooklyn Nets                        166
New Orleans Pelicans                 147
New Orleans Hornets                  146
Vancouver Grizzlies                   90
Kansas City Kings                     85
San Diego Clippers                    73
New Orleans/Oklahoma City Hornets     32
Name: count, dtype: int64

In [21]:
from itertools import combinations

In [22]:
names = ["John","Mary","Rob","Susan","Violet"]
birthday = ["March 5th","Sept 20th","March 39","July 23","Sept 23"]

In [23]:
list(combinations(birthday,2))

[('March 5th', 'Sept 20th'),
 ('March 5th', 'March 39'),
 ('March 5th', 'July 23'),
 ('March 5th', 'Sept 23'),
 ('Sept 20th', 'March 39'),
 ('Sept 20th', 'July 23'),
 ('Sept 20th', 'Sept 23'),
 ('March 39', 'July 23'),
 ('March 39', 'Sept 23'),
 ('July 23', 'Sept 23')]

In [24]:
list(combinations(names,2))

[('John', 'Mary'),
 ('John', 'Rob'),
 ('John', 'Susan'),
 ('John', 'Violet'),
 ('Mary', 'Rob'),
 ('Mary', 'Susan'),
 ('Mary', 'Violet'),
 ('Rob', 'Susan'),
 ('Rob', 'Violet'),
 ('Susan', 'Violet')]

We can see how March 5th (John and Rob) are the same dates.Using Pandas

In [28]:
names_df = pd.DataFrame(combinations(names,2),columns = ['Person 1','Person 2'])
names_df

  Person 1 Person 2
0     John     Mary
1     John      Rob
2     John    Susan
3     John   Violet
4     Mary      Rob
5     Mary    Susan
6     Mary   Violet
7      Rob    Susan
8      Rob   Violet
9    Susan   Violet

In [30]:
birthday_df = pd.DataFrame(combinations(birthday,2),columns =['Birthday 1','Birthday 2'])
birthday_df

  Birthday 1 Birthday 2
0  March 5th  Sept 20th
1  March 5th   March 39
2  March 5th    July 23
3  March 5th    Sept 23
4  Sept 20th   March 39
5  Sept 20th    July 23
6  Sept 20th    Sept 23
7   March 39    July 23
8   March 39    Sept 23
9    July 23    Sept 23

combining it

In [36]:
df = pd.concat([names_df,birthday_df],axis = 1)
df

  Person 1 Person 2 Birthday 1 Birthday 2
0     John     Mary  March 5th  Sept 20th
1     John      Rob  March 5th   March 39
2     John    Susan  March 5th    July 23
3     John   Violet  March 5th    Sept 23
4     Mary      Rob  Sept 20th   March 39
5     Mary    Susan  Sept 20th    July 23
6     Mary   Violet  Sept 20th    Sept 23
7      Rob    Susan   March 39    July 23
8      Rob   Violet   March 39    Sept 23
9    Susan   Violet    July 23    Sept 23