In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('Fifa.csv')

In [10]:
df2 = pd.read_csv('cleaned_2017-18.csv')

In [7]:
df1.head()

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640

In [11]:
df2.head()

,rk,player,nation,pos,squad,comp,age,born,Matches Played,Avg Mins per Match,...,Total Shots,% Shots on target,Shots p 90,Goals per shot,Goals per shot on target,% Aerial Duels won,Shot creating actions p 90,Goal creating actions p 90,Crosses Stopped,season
0,1,Patrick van Aanholt,Netherlands,DF,Crystal Palace,Premier League,26,1990,28,2184,...,33,33.3,0.45,0.15,0.45,54.5,1.90,0.16,0,2017-2018
1,2,Rolando Aarons,England,MF,Newcastle Utd,Premier League,21,1995,4,139,...,2,0.0,0.00,0.00,0.00,25.0,0.65,0.00,0,2017-2018
2,3,Rolando Aarons,England,MF,Hellas Verona,Serie A,21,1995,11,517,...,3,0.0,0.00,0.00,0.00,37.5,0.87,0.00,0,2017-2018
3,4,Ignazio Abate,Italy,DF,Milan,Serie A,30,1986,17,1057,...,4,50.0,0.17,0.25,0.50,55.6,2.30,0.34,0,2017-2018
4,5,Aymen Abdennour,Tunisia,DF,Marseille,Ligue 1,27,1989,8,499,...,2,50.0,0.18,0.00,0.00,50.0,0.36,0.00,0,2017-2018

Data Wrangling Activities

1.Merge df1 and df2 with a left join

In [32]:
df = df1.merge(df2,how = 'left',left_on = 'Name',right_on = 'player')
df

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score,rk,...,Total Shots,% Shots on target,Shots p 90,Goals per shot,Goals per shot on target,% Aerial Duels won,Shot creating actions p 90,Goal creating actions p 90,Crosses Stopped,season
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.650,1660,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.350,1620,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.200,1480,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.500,1695,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.400,1640,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19711,Kohei Okuno,Japan,CDM,21,63,71,Gamba Osaka,1.100,1717,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19712,Riku Danzaki,Japan,RW,22,64,71,Motherwell,1.200,1607,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19713,Hayato Fukushima,Japan,CB,21,59,68,Shonan Bellmare,0.475,1347,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19714,Ömer Tokaç,Turkey,LW,18,57,71,Shonan Bellmare,0.220,1481,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19715,Ko Sawada,Japan,CAM,28,60,60,Shonan Bellmare,0.250,1636,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.head()

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score,rk,...,Total Shots,% Shots on target,Shots p 90,Goals per shot,Goals per shot on target,% Aerial Duels won,Shot creating actions p 90,Goal creating actions p 90,Crosses Stopped,season
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df.head(1).T

                                             0
Name                        Agostinho Mabululu
Country                                 Angola
Position                                    LW
Age                                         30
Overall_Rating                              68
...                                        ...
% Aerial Duels won                         NaN
Shot creating actions p 90                 NaN
Goal creating actions p 90                 NaN
Crosses Stopped                            NaN
season                                     NaN

[74 rows x 1 columns]

2.Are there any mismatch in resulting sum

In [35]:
df['Name'].isna().any()

np.False_

3.How many rows could not be matched

In [36]:
df['Name'].isna().sum()

np.int64(0)

4.Extract the name of the palyers that coudnot be matched

In [37]:
df.loc[df['Name'].isna()]

Empty DataFrame
Columns: [Name, Country, Position, Age, Overall_Rating, Future Potential, Team, Value Per M$, Total_Stats Score, rk, player, nation, pos, squad, comp, age, born, Matches Played, Avg Mins per Match, Goals, Assists, Goals & Assists, Non Penalty Goals, Penalty Kicks Made, Expected Goals, Exp NPG, Progressive Carries, Progressive Passes, Goals p 90, Assists p 90, Tackles attempted, Tackles Won, % Dribbles tackled, Shots blocked, Passes blocked, Interceptions, Clearances, Errors made, Goals Against, Goals against p 90, Saves, Saves %, Clean Sheets, % Clean sheets, % Penalty saves, Passes Completed, Passes Attempted, Pass completion %, Progressive passes distance, % Short pass completed, % Medium passes completed, % Long passes completed, Key passes, 1/3, Passes into penalty area, touches_def_pen, Take ons attempted, % Successful take-ons, Times tackled during take-on, carries_prgc, carries final 3rd, carries penalty area, Possessions lost, Goals Scored, Total Shots, % Shots on target, Shots p 90, Goals per shot, Goals per shot on target, % Aerial Duels won, Shot creating actions p 90, Goal creating actions p 90, Crosses Stopped, season]
Index: []

[0 rows x 74 columns]

7.remove unncessary columns

In [38]:
df.head()

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score,rk,...,Total Shots,% Shots on target,Shots p 90,Goals per shot,Goals per shot on target,% Aerial Duels won,Shot creating actions p 90,Goal creating actions p 90,Crosses Stopped,season
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
columns_to_drop = [
    "% Shots on target",
    "rk",
    "Value Per M$",
    "Shot creating actions p 90"
]
# use drop method

In [50]:
df.tail()

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score,player,...,carries penalty area,Possessions lost,Goals Scored,Total Shots,Shots p 90,Goals per shot,Goals per shot on target,Goal creating actions p 90,Crosses Stopped,season
19711,Kohei Okuno,Japan,CDM,21,63,71,Gamba Osaka,1.100,1717,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19712,Riku Danzaki,Japan,RW,22,64,71,Motherwell,1.200,1607,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19713,Hayato Fukushima,Japan,CB,21,59,68,Shonan Bellmare,0.475,1347,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19714,Ömer Tokaç,Turkey,LW,18,57,71,Shonan Bellmare,0.220,1481,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19715,Ko Sawada,Japan,CAM,28,60,60,Shonan Bellmare,0.250,1636,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df1.head()

,Name,Country,Position,Age,Overall_Rating,Future Potential,Team,Value Per M$,Total_Stats Score
0,Agostinho Mabululu,Angola,LW,30,68,68,Ittihad Alexandria,0.65,1660
1,Mahmoud Gennesh,Egypt,GK,35,67,67,Ittihad Alexandria,0.35,1620
2,Sobhi Suleiman,Egypt,GK,28,63,65,Ittihad Alexandria,0.20,1480
3,Mahmoud Alaa,Egypt,CB,32,68,68,Ittihad Alexandria,0.50,1695
4,Mahmoud Shabana,Egypt,CB,30,66,66,Ittihad Alexandria,0.40,1640

In [52]:
df2.head()

,rk,player,nation,pos,squad,comp,age,born,Matches Played,Avg Mins per Match,...,Total Shots,% Shots on target,Shots p 90,Goals per shot,Goals per shot on target,% Aerial Duels won,Shot creating actions p 90,Goal creating actions p 90,Crosses Stopped,season
0,1,Patrick van Aanholt,Netherlands,DF,Crystal Palace,Premier League,26,1990,28,2184,...,33,33.3,0.45,0.15,0.45,54.5,1.90,0.16,0,2017-2018
1,2,Rolando Aarons,England,MF,Newcastle Utd,Premier League,21,1995,4,139,...,2,0.0,0.00,0.00,0.00,25.0,0.65,0.00,0,2017-2018
2,3,Rolando Aarons,England,MF,Hellas Verona,Serie A,21,1995,11,517,...,3,0.0,0.00,0.00,0.00,37.5,0.87,0.00,0,2017-2018
3,4,Ignazio Abate,Italy,DF,Milan,Serie A,30,1986,17,1057,...,4,50.0,0.17,0.25,0.50,55.6,2.30,0.34,0,2017-2018
4,5,Aymen Abdennour,Tunisia,DF,Marseille,Ligue 1,27,1989,8,499,...,2,50.0,0.18,0.00,0.00,50.0,0.36,0.00,0,2017-2018

9.Convert birthday to a DateTime object

In [53]:
pd.to_datetime(df['born'])

0       NaT
1       NaT
2       NaT
3       NaT
4       NaT
         ..
19711   NaT
19712   NaT
19713   NaT
19714   NaT
19715   NaT
Name: born, Length: 19716, dtype: datetime64[ns]